name: Build logx_decrypt exe
on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build single exe
        run: |
          pyinstaller -F -c logx_decrypt.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: logx_decrypt-windows
          path: dist/logx_decrypt.exe
