name: Build logx_decrypt exe
on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyinstaller-hooks-contrib

      - name: Build exe（保留控制台调试，先不要加 -w）
        run: |
          pyinstaller -F logx_decrypt_gui.py --additional-hooks-dir=%PYTHONPATH%\pyinstaller_hooks_contrib\hooks

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: logx_decrypt-windows
          path: dist/logx_decrypt_gui.exe
